module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.22.0

toolchain go1.24.1

replace k8s.io/apimachinery v0.21.3 => github.com/mutagen-io/apimachinery v0.21.3-mutagen1

require github.com/mutagen-io/mutagen v0.18.1 // cmd/mutagen
