{
 "title": "IOSXR_Device_Health_Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "SHOW TAG VALUES WITH KEY=\"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization - RP0",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT mean(\"total_cpu_one_minute\") FROM \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RP0/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    },
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT max(\"total-cpu-one-minute\") FROM \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP0/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization - RP1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT max(\"total-cpu-one-minute\") FROM \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    },
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "query": "SELECT max(\"total-cpu-one-minute\") FROM \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP1/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used - RP0",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system_ram_memory\") - last(\"free_application_memory\")) * 100 / last(\"system_ram_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RP0/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "free-application-memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system_ram_memory\") - last(\"free_application_memory\")) * 100 / last(\"system_ram_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RSP0/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "free-application-memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used - RP1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system_ram_memory\") - last(\"free_application_memory\")) * 100 / last(\"system_ram_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RP1/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "free-application-memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system_ram_memory\") - last(\"free_application_memory\")) * 100 / last(\"system_ram_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RSP1/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "free-application-memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memory Use",
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "SELECT (last(\"uptime\")) FROM \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Summary",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "alias": "Total Interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "query": "SELECT last(\"interface-counts__interface-count\") FROM \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "interface_counts/interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/up_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Interfaces Admin Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/admin_down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load Historical - 0/RP0/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_node_name]] - CPU 1 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 5 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_five_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 1 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP0/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 5 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_five_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP0/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load Historical - 0/RP1/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_node_name]] - CPU 1 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 5 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_five_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 1 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP1/CPU0" }
     ]
    },
    {
     "alias": "[[tag_node_name]] - CPU 5 min",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_five_minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP1/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory - 0/RP0/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Free Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "select": [
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    },
    {
     "alias": "Free Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "select": [
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP0/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory - 0/RP0/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (\"system_ram_memory\" - \"free_application_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RP0/CPU0') AND $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    },
    {
     "alias": "Used Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (\"system_ram_memory\" - \"free_application_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RSP0/CPU0') AND $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory - 0/RP1/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Free Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "select": [
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    },
    {
     "alias": "Free Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "select": [
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RSP1/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory - 0/RP1/CPU0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (\"system_ram_memory\" - \"free_application_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RP1/CPU0') AND $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    },
    {
     "alias": "Used Mem - [[tag_node_name]]",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (\"system_ram_memory\" - \"free_application_memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE (\"source\" =~ /^$Node$/ AND \"node_name\" = '0/RSP1/CPU0') AND $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP1/CPU0" }
     ]
    }
   ]
  },
  {
   "title": "Device Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface_name]] IN",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT non_negative_derivative(\"bytes-received\", 1s) *8 FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY \"interface-name\"",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "[[tag_interface_name]] OUT",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Drops and Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Input Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "input_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Output Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "output_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Input Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "input_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Output Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "output_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Input Queue Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "input_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Output Queue Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "output_queue_drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  { "title": "Optical parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Power levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]].[[tag_lane-data__lane-index]] RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "lane-data__lane-index" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT distinct(\"lane-data__receive-power\")  / 100 FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY time($__interval), \"name\", \"lane-data__lane-index\"",
     "select": [
      [
       { "params": [ "lane_data/receive_power" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "[[tag_name]].[[tag_lane-data__lane-index]] TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "lane-data__lane-index" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       { "params": [ "lane_data/transmit_power" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Laser Bias Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]].[[tag_lane-data__lane-index]] RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "lane-data__lane-index" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "select": [
      [
       {
        "params": [
         "lane_data/laser_bias_current_milli_amps"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  }
 ]
}