{
 "title": "IOSXR_Device_MPLS_TE_Metrics_Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "SHOW TAG VALUES WITH KEY=\"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "RSVP Bandwidth Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Allocated RSVP BW, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
     "query": "SELECT \"bandwidth-information__pre-standard-dste-interface__allocated-bit-rate\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief\" WHERE \"source\" =~ /^$Node$/ AND \"interface-name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface-name\"",
     "select": [
      [
       {
        "params": [
         "bandwidth_information/pre_standard_dste_interface/allocated_bit_rate"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "RSVP Maximum Bandwidth ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "MAX RSVP BW, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/interface-briefs/interface-brief",
     "select": [
      [
       {
        "params": [
         "bandwidth_information/pre_standard_dste_interface/max_flow_bandwidth"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "MPLS-TE Tunnels Summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Auto-BW tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "query": "SELECT \"auto-bandwidth-tunnels\" FROM \"Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "auto_bandwidth_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Backup tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "backup_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bandwidth protected tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "bw_protected_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-headend tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_head_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-midpoint tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_mid_point_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-protected tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_protected_interfaces" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Link protected tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "link_protected_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Node protected tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "node_protected_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "P2P headend tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_head_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Protected headend tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "protected_head_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Protected midpoint tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "protected_mid_point_tunnels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Midpoint tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_mid_point_s2_ls" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Tail-end tunnels",
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_tail_s2_ls" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "MPLS-TE Tunnel Status Changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Auto-BW tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "auto_bandwidth_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Backup tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "backup_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bandwidth protected tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "bw_protected_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-headend tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_head_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-midpoint tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_mid_point_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "FRR-protected tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "frr_protected_interfaces" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Link protected tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "link_protected_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Node protected tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "node_protected_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "P2P headend tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_head_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Protected headend tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "protected_head_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Protected midpoint tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "protected_mid_point_tunnels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Midpoint tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_mid_point_s2_ls" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Tail-end tunnels change",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-mpls-te-oper:mpls-te/tunnels/summary",
     "select": [
      [
       { "params": [ "p2p_tail_s2_ls" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "RSVP Message Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Bundle RX ACK, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "select": [
      [
       { "params": [ "ack" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX HELLO, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "bundle_received_messages/hello" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX PATH, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "bundle_received_messages/path" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX PATH ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/path_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX PATH TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/path_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX RESV, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/reservation"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX RESV CONFIRM, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/reservation_confirm"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX RESV ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/reservation_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle RX RESV TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_received_messages/reservation_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX ACK, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/ack"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX HELLO, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/hello"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX PATH, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/path"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX PATH ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/path_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX PATH TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/path_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX RESV, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/reservation"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX RESV CONFIRM, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/reservation_confirm"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX RESV ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/reservation_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Bundle TX RESV TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "bundle_transmitted_messages/reservation_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX ACK, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "select": [
      [
       { "params": [ "received_messages/ack" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX HELLO, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "received_messages/hello" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX PATH, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "received_messages/path" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX PATH ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "received_messages/path_error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX PATH TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "received_messages/path_tear" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX RESV, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "received_messages/reservation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX RESV CONFIRM, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "received_messages/reservation_confirm"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX RESV ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "received_messages/reservation_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "RX RESV TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "received_messages/reservation_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX ACK, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "select": [
      [
       { "params": [ "transmitted_messages/ack" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX HELLO, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "transmitted_messages/hello" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX PATH, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "transmitted_messages/path" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX PATH ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "transmitted_messages/path_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" },
      { "condition": "AND", "key": "interface_name", "operator": "=~", "value": "/Bundle.*/" }
     ]
    },
    {
     "alias": "TX PATH TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       { "params": [ "transmitted_messages/path_tear" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX RESV, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "transmitted_messages/reservation"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX RESV CONFIRM, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "transmitted_messages/reservation_confirm"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX RESV ERROR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"bundle-received-messages/hello\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE \"source\" =~ /^$Node$/ AND \"interface_name\" =~ /Bundle.*/ AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "transmitted_messages/reservation_error"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "TX RESV TEAR, [[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message",
     "query": "SELECT \"transmitted-messages/reservation-tear\" FROM \"Cisco-IOS-XR-ip-rsvp-oper:rsvp/counters/interface-messages/interface-message\" WHERE (\"source\" =~ /^$Node$/) AND $timeFilter GROUP BY \"interface_name\"",
     "select": [
      [
       {
        "params": [
         "transmitted_messages/reservation_tear"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  }
 ]
}